version: '2.4'

services:
    web:
        image: nginx:stable-alpine

        environment:
            TZ: Europe/Moscow

        volumes:
            - ./dev.conf:/etc/nginx/conf.d/dev.conf
            - ./src:/var/www

        links:
            - php
        expose:
            - "8080"
        ports:
            - "${PORT_ON_LOCALHOST}:8080"

        container_name: ${COMPOSE_PROJECT_NAME}-web
        restart: always

    php:
        build: .
        image: php8:inittask_for_pp

        environment:
            TZ: Europe/Moscow
            MYSQL_HOST: &dbhost ${COMPOSE_PROJECT_NAME}-db
            MYSQL_DATABASE: &database ${DB_DATABASE}
            MYSQL_USER: &user ${DB_USER}
            MYSQL_PASSWORD: &password ${DB_PASSWORD}
            DEBUG: ${DEBUG}
        volumes:
            - ./src:/var/www
            - ./src-db:/db
        container_name: ${COMPOSE_PROJECT_NAME}-php
        restart: always

    db:
        image: mysql:8.0
        container_name: *dbhost
        expose:
            -   "3306"
        environment:
            TZ: Europe/Moscow
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: *database
            MYSQL_USER: *user
            MYSQL_PASSWORD: *password

        volumes:
            - ./db-data:/var/lib/mysql
        restart: always

#    pma:
#        image: phpmyadmin
#        container_name: pma
#        ports:
#            - 8085:80
#        environment:
#            - PMA_ARBITRARY=1
#            - UPLOAD_LIMIT=300M
#        restart: always