version: '2.4'

services:

    #Nginx Service
    nginx:
        image: nginx:stable-alpine
        container_name: ${CONTAINER_NGINX}
        restart: unless-stopped
        environment:
            TZ: ${TIME_ZONE}
        volumes:
            - ./dev.conf:/etc/nginx/conf.d/dev.conf
            - ./src:/var/www
        links:
            - php
        expose:
            - 8080
        ports:
            - ${NGINX_PORT}:8080

    #PHP Service
    php:
        build: .
        image: php8:inittask_for_pp
        container_name: ${CONTAINER_PHP}
        restart: unless-stopped
        environment:
            TZ: ${TIME_ZONE}
            MYSQL_HOST: ${CONTAINER_MYSQL}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            DEBUG: ${DEBUG}
        volumes:
            - ./src:/var/www
            - ./src-db:/db

    mysql:
        image: mysql:8.0
        container_name: ${CONTAINER_MYSQL}
        restart: unless-stopped
        expose:
            -   3306
        environment:
            TZ: Europe/Moscow
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

        volumes:
            - ./db-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        container_name: ${CONTAINER_PHPMYADMIN}
        restart: unless-stopped
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            PMA_HOST: ${CONTAINER_MYSQL}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            UPLOAD_LIMIT: 300M