version: '2.4'

services:
    web:
        image: nginx:stable-alpine

        environment:
            TZ: Europe/Moscow

        volumes:
            - ./dev.conf:/etc/nginx/conf.d/dev.conf
            - ./src:/var/www

        links:
            - php
        expose:
            - "8080"
        ports:
            - "${PORT_ON_LOCALHOST}:8080"

        container_name: ${COMPOSE_PROJECT_NAME}-web
        restart: always

    php:
        build: .
        image: php8:test_for_pp

        environment:
            TZ: Europe/Moscow
            MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}-db
            MYSQL_USER: appuser
            MYSQL_PASSWORD: Ga8MnU6D65
        volumes:
            - ./src:/var/www
        container_name: ${COMPOSE_PROJECT_NAME}-php
        restart: always

    db:
        image: mysql:8.0
        container_name: ${COMPOSE_PROJECT_NAME}-db
        expose:
            -   "3306"
        environment:
            TZ: Europe/Moscow
            MYSQL_ROOT_PASSWORD: 9B9weD3SSse232
            MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}-db
            MYSQL_USER: appuser
            MYSQL_PASSWORD: Ga8MnU6D65

        volumes:
            - ./db-data:/var/lib/mysql
        restart: always

    pma:
        image: phpmyadmin
        container_name: pma
        ports:
            - 8085:80
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=300M
        restart: always